# Generated by Django 4.2.6 on 2023-10-16 20:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=500)),
                ('salary', models.IntegerField(blank=True, default=0)),
                ('job_nature', models.CharField(max_length=500)),
                ('posted_date', models.DateTimeField(default=datetime.datetime(2023, 10, 16, 20, 27, 30, 296779, tzinfo=datetime.timezone.utc))),
                ('last_date', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField()),
                ('company_name', models.CharField(default='', max_length=100)),
                ('company_description', models.CharField(default='', max_length=500)),
                ('company_website', models.CharField(default='', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
